plugins {
    id 'java'
}

group = 'me.user'
version = '1.1'

repositories {
    mavenCentral()
    maven { url = "https://repo.papermc.io/repository/maven-public/" }
}

dependencies {
    // 1.21.1 페이퍼 서버 API를 불러옵니다.
    compileOnly "io.papermc.paper:paper-api:1.21.1-R0.1-SNAPSHOT"
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8' // 한글 깨짐 방지
}